language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli bower
- bower install
script: grunt
before_deploy: cd deployd;ls -l
deploy:
  provider: appfog
  email: dbdjbah@gmail.com
  password:
    secure: Aa63rFrEqUtccFwvd2gD8nUxlpa7LlQU7ypIXsH75NhIS2bemlSBJ4zaRLMeBww6WwwxKV7Y3iUrENozSQL3+YmIuX8pDWeJZT2AxMKijqcM1E9/4aILInUIgTcCnfryIH/bdGuEZFtUczbQBKhAvuE1KYiWUwtHx/wQ3NTTblQ=
  app: rokuman
  on:
    repo: rama2/MediaStream
