language: node_js
node_js:
- '0.10'
before_script:
- npm install -g grunt-cli bower
- bower install
script: grunt

deploy:
  provider: appfog
  email: dbdjbah@gmail.com
  password:
    secure: atNp5DQbet7BfNMXXK9CWZ4rS1H6rYehL3Fp5cYlGqYhkw+cUrJdvNw+rYP1ANthxtsEsV7/nZT8LfgcMV7fIhGhSVFNfTeTKjiCq4fwDf0KL8kfm756vk98co9mdBzDBP1IxQIA11Sw7lyr4nbrB907HeBxy1wQK2PVWjDJa0o=
  app: rokuman
  on:
    repo: rama2/MediaStream
